name: Auto Push to GitLab

on:
  push:
    #branches: [ main ]
  workflow_dispatch:
jobs:
  push_to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
      - uses: actions/checkout@v4
      - name: Setup Gitlab remote
